import './globals.css'

export const metadata = {
  title: 'Contabilidade Completa - Senhor Contábil',
  description: 'Generated by Andresa A Ribeiro',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br">
      <body>{children}</body>
    </html>
  )
}
